import { randomUUID } from "node:crypto"
import { GENERATED_FILE_MAX_BYTES, PPTX_MIME_TYPE, pptxJsonDataSchema } from "@yummy/shared"
import type { PptxJsonData } from "@yummy/shared"

// ---------------------------------------------------------------------------
// JSON extraction
// ---------------------------------------------------------------------------

const PPTX_JSON_PATTERN = /```pptx-json\s*\n([\s\S]*?)\n```/

export function extractPptxJson(text: string): PptxJsonData | null {
  const match = text.match(PPTX_JSON_PATTERN)
  if (!match?.[1]) return null

  try {
    const parsed = JSON.parse(match[1])
    const result = pptxJsonDataSchema.safeParse(parsed)
    return result.success ? result.data : null
  } catch {
    return null
  }
}

// ---------------------------------------------------------------------------
// PPTX generation
// ---------------------------------------------------------------------------

export async function generatePptxBuffer(data: PptxJsonData): Promise<{
  filename: string
  mimeType: string
  byteSize: number
  buffer: Buffer
}> {
  // Dynamic import for ESM compatibility
  const PptxGenJS = (await import("pptxgenjs")).default

  const pptx = new PptxGenJS()

  // 16:9 widescreen layout
  pptx.layout = "LAYOUT_WIDE"

  // --- Title slide (title + subtitle on the same slide) ---
  const titleSlide = pptx.addSlide()
  titleSlide.addText(data.title, {
    x: 0.5,
    y: 1.5,
    w: 9,
    h: 2,
    fontSize: 36,
    bold: true,
    color: "333333",
    align: "center",
  })
  titleSlide.addText("Generated by Yummy Chat", {
    x: 0.5,
    y: 3.5,
    w: 9,
    h: 1,
    fontSize: 14,
    color: "999999",
    align: "center",
  })

  // --- Content slides ---
  for (const slide of data.slides) {
    const s = pptx.addSlide()

    // Slide title
    s.addText(slide.title, {
      x: 0.7,
      y: 0.4,
      w: 8.5,
      h: 0.8,
      fontSize: 24,
      bold: true,
      color: "2B579A",
    })

    // Bullet points — fresh array created per slide
    s.addText(
      slide.bullets.map((b) => ({
        text: b,
        options: {
          bullet: true,
          fontSize: 16,
          color: "333333",
          breakType: "none",
        },
      })),
      {
        x: 0.7,
        y: 1.5,
        w: 8.5,
        h: 4.5,
        valign: "top",
      },
    )
  }

  // --- Closing slide ---
  const cs = pptx.addSlide()
  cs.addText(data.closing || "Thank you", {
    x: 0.5,
    y: 2.0,
    w: 9,
    h: 2,
    fontSize: 28,
    bold: true,
    color: "333333",
    align: "center",
  })

  // --- Generate buffer ---
  const buffer = (await pptx.write({ outputType: "nodebuffer" })) as Buffer

  // Size check
  if (buffer.length > GENERATED_FILE_MAX_BYTES) {
    throw new Error("PPTX_FILE_TOO_LARGE")
  }

  const fileId = randomUUID()
  const filename = `slides-${fileId.slice(0, 8)}.pptx`

  return {
    filename,
    mimeType: PPTX_MIME_TYPE,
    byteSize: buffer.length,
    buffer,
  }
}
