import type PptxGenJS from "pptxgenjs"
import { THEME } from "./theme"

// ---------------------------------------------------------------------------
// Yummy Chat slide master — persistent brand elements applied to every slide.
//
// Defines:
//  - Background color (subtle off-white from the theme palette)
//  - Two subtle horizontal grid lines (upper + lower thirds) for visual rhythm
//  - Footer bar with a primary-color accent rule on its top edge
//  - Footer text "Generated by Yummy Chat"
//  - Slide number (bottom-right, muted)
// ---------------------------------------------------------------------------

export function defineYummyMaster(pptx: PptxGenJS): void {
  pptx.defineSlideMaster({
    title: THEME.masterName,
    background: { color: THEME.colors.background },
    objects: [
      // Subtle horizontal grid line — upper third
      {
        line: {
          x: 0,
          y: 2.5,
          w: "100%",
          h: 0,
          line: { color: THEME.colors.border, width: 0.5 },
        },
      },
      // Subtle horizontal grid line — lower third
      {
        line: {
          x: 0,
          y: 5.0,
          w: "100%",
          h: 0,
          line: { color: THEME.colors.border, width: 0.5 },
        },
      },
      // Footer bar background
      {
        rect: {
          x: 0,
          y: THEME.layout.footerY,
          w: "100%",
          h: THEME.layout.footerHeight,
          fill: { color: THEME.colors.surface },
        },
      },
      // Footer accent line (primary color, top edge of footer)
      {
        line: {
          x: 0,
          y: THEME.layout.footerY,
          w: "100%",
          h: 0,
          line: { color: THEME.colors.primary, width: 1 },
        },
      },
      // Footer text — "Generated by Yummy Chat"
      {
        text: {
          text: THEME.footer,
          options: {
            x: THEME.layout.margin,
            y: THEME.layout.footerY + 0.05,
            w: 6,
            h: 0.4,
            fontSize: THEME.typography.footerSize,
            color: THEME.colors.textLight,
            fontFace: THEME.typography.fontFace,
          },
        },
      },
    ],
    slideNumber: {
      x: THEME.layout.width - 1.0,
      y: THEME.layout.footerY + 0.05,
      color: THEME.colors.textLight,
      fontSize: THEME.typography.footerSize,
      fontFace: THEME.typography.fontFace,
    },
  })
}
