// ---------------------------------------------------------------------------
// Yummy Chat PPTX theme — reusable color palette + typography config.
// All colors are hex strings WITHOUT "#" (pptxgenjs convention).
// ---------------------------------------------------------------------------

export const THEME = {
  colors: {
    primary: "2B579A", // deep brand blue (titles, accents)
    secondary: "6C757D", // muted gray (subtitles, secondary text)
    background: "FAFAFA", // slide background (subtle off-white)
    surface: "FFFFFF", // card / panel background
    textDark: "333333", // primary body text
    textLight: "999999", // muted text / footer
    border: "E0E0E0", // subtle card borders
    accent: "FF6B35", // warm accent (accent bars, highlights)
  },
  typography: {
    fontFace: "Arial",
    titleSize: 40,
    subtitleSize: 16,
    slideTitleSize: 26,
    bodySize: 16,
    bulletSize: 18,
    closingSize: 32,
    footerSize: 9,
    bulletCharCode: "2022", // •
  },
  layout: {
    width: 13.33, // LAYOUT_WIDE
    height: 7.5,
    margin: 0.7,
    footerHeight: 0.5,
    footerY: 7.0,
  },
  footer: "Generated by Yummy Chat",
  masterName: "YUMMY_MASTER",
} as const

export type Theme = typeof THEME
